name: Github Pages

on:
  push:
    branches:
      - master
    paths:
      - dice-game-ui-angular/**
      - engine/**

jobs:
  build:
    runs-on: windows-latest

    env:
      working_directory: .\dice-game-ui-angular

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: NPM install
        run: npm install
        working-directory: ${{env.working_directory}}

      - name: Build
        run: npm run gh-pages
        working-directory: ${{env.working_directory}}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
