name: Github Pages

on:
  push:
    branches: 'master'
    paths:
      - 'dice-game-ui-angular/**'
      - 'engine/**'

jobs:
  build:
    runs-on: windows-latest

    env:
      working_directory: .\dice-game-ui-angular

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: NPM install
        run: npm install
        working-directory: ${{env.working_directory}}

      - name: Linting
        run: npm run lint
        working-directory: ${{env.working_directory}}
      
      - name: Replace tokens
        uses: cschleiden/replace-tokens@v1.0
        with:
          files: '["dice-game-ui-angular/src/environments/environment.prod.ts"]'
        env:
          googleClientId: ${{ secrets.GOOGLE_CLIENT_ID }}
          fbAuthClientId: ${{ secrets.FACEBOOK_CLIENT_ID }}

      - name: Build
        run: npm run gh-pages
        working-directory: ${{env.working_directory}}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
